'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
export default function InviteLink({project}:{project:string}){
 const [url,setUrl]=useState(''),[expires,setExpires]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function request(action:string){const r=await fetch('/api/invites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,project})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);return d}
 useEffect(()=>{let active=true;request('status').then(d=>{if(active)setExpires(d.expiresAt)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[project]);
 async function create(){setBusy(true);setError('');try{const d=await request('create');setUrl(window.location.origin+'/join#'+d.token);setExpires(d.expiresAt)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel invite-panel"><div><h2>Invite teammates</h2><p className="subtext">Anyone with this link can sign in and join this project. Share it only with your teammates.</p></div>{error&&<p className="error">{error}</p>}{url&&<label className="invite-url">Invitation link<input readOnly value={url} onFocus={e=>e.target.select()}/></label>}<div className="flex flex-wrap gap-3">{url&&<button className="btn primary" onClick={async()=>{try{await navigator.clipboard.writeText(url);toast.success('Invitation link copied.')}catch{setError('Select the link above and copy it manually.')}}}>Copy invite link</button>}<button className="btn" disabled={busy} onClick={create}>{busy?'Updating…':expires?'Replace invite link':'Create invite link'}</button>{expires&&<button className="btn subtle" disabled={busy} onClick={async()=>{setBusy(true);try{await request('revoke');setUrl('');setExpires(null);setError('');toast.success('Invitation link revoked.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Revoke link</button>}</div>{expires&&<small>Expires {new Date(expires).toLocaleString()}. Replacing the link disables the previous one. Revoking a link does not remove teammates who already joined.</small>}</section>
}
