import {aiConfigured,isSiteOwner} from '@/lib/ai-config';
import {identity,runtime,projectFor,failure,sameOrigin} from '@/lib/server';
import type {Project} from '@/lib/model';
export async function GET(){try{const user=await identity();const {DB}=runtime();const profile=await DB.prepare('SELECT * FROM profiles WHERE id=?').bind(user.userId).first();const result=await DB.prepare('SELECT p.* FROM projects p WHERE p.owner=? OR EXISTS(SELECT 1 FROM memberships m WHERE m.project_id=p.id AND m.email=?)').bind(user.userId,user.email).all<{data:string;version:number;owner:string}>();return Response.json({user:{id:user.userId,name:profile?.name||user.fullName||user.email.split('@')[0],email:user.email},projects:result.results.map(r=>({...JSON.parse(r.data),version:r.version,owner:r.owner})),aiReady:await aiConfigured(),canConfigureAI:isSiteOwner(user.email),emailReady:false});}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const user=await identity();const {DB}=runtime();const body:any=await req.json();if(body.action==='profile'){const name=String(body.name||'').trim().slice(0,80);if(!name)return Response.json({error:'Please enter your name.'},{status:400});await DB.prepare('INSERT INTO profiles (id,name,email) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email').bind(user.userId,name,user.email).run();return Response.json({ok:true})}
const p=body.project as Project;if(!p||!p.name?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(p.due)||!Array.isArray(p.tasks)||!Array.isArray(p.members)||!Array.isArray(p.milestones)||!p.availability||JSON.stringify(p).length>300000||p.tasks.length>500||p.members.length>30||p.milestones.length>100||!Number.isInteger(p.reminderHours)||p.reminderHours<1||p.reminderHours>168)return Response.json({error:'Check the project details and try again.'},{status:400});
if(p.tasks.some(t=>!t.id||!t.title?.trim()||!['todo','progress','done'].includes(t.status)||!/^\d{4}-\d{2}-\d{2}$/.test(t.due))||p.members.some(m=>!m.id||!m.name?.trim()||!/^\S+@\S+\.\S+$/.test(m.email))||p.milestones.some(m=>!m.id||!m.title?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(m.due)))return Response.json({error:'Check task, milestone, and member details.'},{status:400});
if(body.action==='create'){if(p.due<new Date().toISOString().slice(0,10))return Response.json({error:'Choose a future project deadline.'},{status:400});p.id=crypto.randomUUID();p.version=0;p.owner=user.userId;p.members=[{id:user.userId,name:p.members.find(m=>m.email===user.email)?.name||user.displayName,email:user.email},...p.members.filter(m=>m.email.toLowerCase()!==user.email)];await DB.batch([DB.prepare('INSERT INTO projects (id,owner,data,version) VALUES (?,?,?,0)').bind(p.id,user.userId,JSON.stringify(p)),...p.members.map(m=>DB.prepare('INSERT INTO memberships(id,project_id,email) VALUES (?,?,?)').bind(crypto.randomUUID(),p.id,m.email.toLowerCase()))]);return Response.json({project:p});}
const existing=await projectFor(p.id,user);const previous=JSON.parse(existing.data) as Project;
const ownId=previous.members.find(m=>m.email.toLowerCase()===user.email)?.id||user.userId;const newSlots=p.availability[ownId]||[];if(!Array.isArray(newSlots)||newSlots.length>100||newSlots.some((slot:string)=>typeof slot!=='string'||!Number.isFinite(Date.parse(slot))||(!previous.availability[ownId]?.includes(slot)&&Date.parse(slot)<Date.now())))return Response.json({error:'Availability must contain future dates and times.'},{status:400});p.availability={...previous.availability,[ownId]:newSlots};
if(existing.version!==p.version)return Response.json({error:'A teammate updated this project. Reload the workspace before saving again.'},{status:409});
if(existing.owner!==user.userId){p.members=previous.members;p.owner=existing.owner;const memberId=previous.members.find(m=>m.email.toLowerCase()===user.email)?.id||user.userId;p.availability={...previous.availability,[memberId]:p.availability[memberId]||[]};}
const statements=[DB.prepare('UPDATE projects SET data=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(p),p.id,p.version),DB.prepare('DELETE FROM memberships WHERE project_id=? AND EXISTS(SELECT 1 FROM projects WHERE id=? AND version=? AND data=?)').bind(p.id,p.id,p.version+1,JSON.stringify(p)),...p.members.map(m=>DB.prepare('INSERT INTO memberships(id,project_id,email) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM projects WHERE id=? AND version=? AND data=?)').bind(crypto.randomUUID(),p.id,m.email.toLowerCase(),p.id,p.version+1,JSON.stringify(p)))];const result=await DB.batch(statements);if(!result[0].meta.changes)return Response.json({error:'A teammate updated this project. Reload before saving.'},{status:409});return Response.json({project:{...p,owner:existing.owner,version:p.version+1}});
}catch(e){return failure(e)}}
